#!/bin/sh

start() {

   echo -n Starting reset timer...
   start-stop-daemon -S -N 18 -b -x /usr/bin/timed_reset.sh
   echo OK
}

stop() {
   echo
}

restart() {
   echo
}

case "$1" in
  start)
    start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

